TaxiBooking/Models/Attachment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TaxiBooking.Models
{
    public class Attachment
    {
        public Attachment()
        {
            CreatedAt = DateTime.Now;
            IsActive = true;
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        [Required]
        public int CarId { get; set; }
        [Required]
        public string File { get; set; }
        [Required]
        public int Type { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
        public virtual Car Car { get; set; }
    }
}

TaxiBooking/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaxiBooking.Models
{
    public class Car
    {
        public Car()
        {
            Attachments = new HashSet<Attachment>();
            IsActive = true;
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public int CarNo { get; set; }
        [Required]
        [MaxLength(256)]
        public string CarColor { get; set; }
        [Required]
        [MaxLength(256)]
        public string CarModel { get; set; }
        [Required]
        public DateTime ExpiryDate { get; set; }
        [Required]
        public DateTime CreatedAt { get; set; }
        [Required]
        [MaxLength(256)]
        public string OwnerName { get; set; }
        public bool IsActive { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
    }
}

TaxiBooking/ViewModels/CreateCarModel.cs
using TaxiBooking.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;
using Microsoft.AspNetCore.Http;

namespace TaxiBooking.ViewModels
{
    public class CreateCarModel
    {
        [Required]
        public int CarNo { get; set; }
        [Required]
        [MaxLength(256)]
        public string CarColor { get; set; }
        [Required]
        [MaxLength(256)]
        public string CarModel { get; set; }
        [Required]
        public DateTime ExpiryDate { get; set; }
        [Required]
        public DateTime CreatedAt { get; set; }
        [Required]
        [MaxLength(256)]
        public string OwnerName { get; set; }
        public List<IFormFile> Attachments { get; set; }
    }
}

TaxiBooking/ViewModels/UpdateCarModel.cs
using TaxiBooking.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;
using Microsoft.AspNetCore.Http;

namespace TaxiBooking.ViewModels
{
    public class UpdateCarModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public int CarNo { get; set; }
        [Required]
        [MaxLength(256)]
        public string CarColor { get; set; }
        [Required]
        [MaxLength(256)]
        public string CarModel { get; set; }
        [Required]
        public DateTime ExpiryDate { get; set; }
        [Required]
        public DateTime CreatedAt { get; set; }
        [Required]
        [MaxLength(256)]
        public string OwnerName { get; set; }
        public List<IFormFile> Attachments { get; set; }
    }
}

TaxiBooking/Controllers/CarsController.cs
using TaxiBooking.Context;
using TaxiBooking.Models;
using TaxiBooking.ViewModels;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Data.Entity;
using System.Collections.Generic;
using System.Net;

namespace TaxiBooking.Controllers
{
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarsController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Cars
        public ActionResult Index()
        {
            IEnumerable<Car> cars = _context.Cars.Include(x => x.Attachments).ToList();
            return View(cars);
        }

        [HttpGet]
        public ActionResult Details(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var cars = _context.Cars.Find(id);
            if(cars == null)
            return HttpNotFound();

            return View(cars);
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CreateCarModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Attachments = model.Attachments;
                return View("Create", model);
            }
            Car car = new Car()
            {
                //Attachments = model.Attachments,
                CarNo = model.CarNo,
                CarColor = model.CarColor,
                CarModel = model.CarModel,
                ExpiryDate = model.ExpiryDate,
                CreatedAt = model.CreatedAt,
                OwnerName = model.OwnerName,
            };
            _context.Cars.Add(car);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TaxiBooking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TaxiBooking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TaxiBooking/Views/Cars/Create.cshtml
@model TaxiBooking.ViewModels.CreateCarModel
@{
    ViewBag.Title = "Create";
}

<h3 class="text-primary">Create</h3>

<hr />

@using (Html.BeginForm("Save", "Cars"))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.CarNo)
        @Html.TextBoxFor(m => m.CarNo, " " , new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CarNo, null, new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.CarColor)
        @Html.TextBoxFor(m => m.CarColor, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CarColor, null, new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.CarModel)
        @Html.TextBoxFor(m => m.CarModel, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CarModel, null, new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.OwnerName)
        @Html.TextBoxFor(m => m.OwnerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.OwnerName, null, new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.CreatedAt)
        @Html.TextBoxFor(m => m.CreatedAt, " ", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CreatedAt, null, new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.ExpiryDate)
        @Html.TextBoxFor(m => m.ExpiryDate, " ", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ExpiryDate, null, new { @class = "text-danger" })
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Save</button>
}

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

TaxiBooking/Views/Cars/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

TaxiBooking/Views/Cars/Index.cshtml
@model IEnumerable<TaxiBooking.Models.Car>
@{
    ViewBag.Title = "Index";
}

<h2 class="text-primary">Cars</h2>

<hr />

<a href="@Url.Action("Create")" class="btn btn-primary my-4"><i class="icofont-plus"></i> Add New</a>

@if (!Model.Any())
{

}
else
{
    <table class="table">
        <thead>
            <tr>

                <th>Car No</th>
                <th>Car Color</th>
                <th>Car Model</th>
                <th>Expiry Date</th>
                <th>Car year of manufacture</th>
                <th>Owner name</th>
                <th>Attachment</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var car in Model)
            {
                <tr>
                    <th>@Html.ActionLink(car.CarNo.ToString(), "Details", "Cars", new { id = car.Id }, null)</th>
                    <th>@car.CarColor</th>
                    <th>@car.CarModel</th>
                    <th>@car.ExpiryDate.ToString("MM/dd/yyyy")</th>
                    <th>@car.CreatedAt.ToString("MM/dd/yyyy")</th>
                    <th>@car.OwnerName</th>
                    <th>
                        <a href="@Url.Action("Attachment", "Cars", new {id = car.Id})" class="btn btn-primary"><i class="icofont-ui-image"></i> Attachment</a>
                    </th>
                    <th>
                        <a href="@Url.Action("Edit", "Cars", new {id = car.Id})" class="btn btn-primary"><i class="icofont-ui-edit"></i> Edit</a>
                        <a href="javascript:;" , class="btn btn-danger"><i class="icofont-ui-delete"></i> Delete</a>
                    </th>
                </tr>
            }
        </tbody>
    </table>
}

TaxiBooking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TaxiBooking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TaxiBooking/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TaxiBooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cars</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Cars</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Cars", "Index", "Cars", null, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cars</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>